# Generated by Django 2.2.2 on 2021-03-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210312_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_number',
        ),
    ]
