# Generated by Django 2.2.2 on 2021-03-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_studentinfo_fathers_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassinfo',
            old_name='class_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='class_type',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='studentclassinfo',
            name='class_short_form',
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('admission_id', 'dept_name')},
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='dept',
        ),
    ]
